from collections.abc import AsyncIterator
from typing import Protocol
from ..groups.models import GroupContext
from ..members.models import Member


class TelegramGateway(Protocol):
    async def resolve_group(self, account_id: int, reference: str) -> GroupContext: ...
    async def get_joined_groups(self, account_id: int) -> list[GroupContext]: ...
    async def iter_participant_pages(self, account_id: int, group: GroupContext, offset: int, limit: int) -> AsyncIterator[list[Member]]: ...
    async def invite_user(self, account_id: int, target: GroupContext, member: Member) -> None: ...
    async def join_group(self, account_id: int, reference: str) -> GroupContext: ...
    async def leave_group(self, account_id: int, group: GroupContext) -> None: ...
