from __future__ import annotations
from enum import StrEnum
class ConnectionState(StrEnum):
    DISCONNECTED='DISCONNECTED';CONNECTING='CONNECTING';AUTH_REQUIRED='AUTH_REQUIRED';READY='READY';ERROR='ERROR';DISABLED='DISABLED'
class OperationState(StrEnum):
    IDLE='IDLE';PREPARING='PREPARING';RUNNING='RUNNING';WAITING_SERVER='WAITING_SERVER';PAUSED='PAUSED';RATE_LIMITED='RATE_LIMITED';RECOVERING='RECOVERING'
class AccountState(StrEnum):
    DISCONNECTED='DISCONNECTED';CONNECTING='CONNECTING';AUTH_REQUIRED='AUTH_REQUIRED';READY='READY';ERROR='ERROR';DISABLED='DISABLED';BUSY='BUSY';WAITING_SERVER='WAITING_SERVER'
class JobState(StrEnum):
    READY='READY';PREPARING='PREPARING';RUNNING='RUNNING';WAITING_SERVER='WAITING_SERVER';PAUSED='PAUSED';RATE_LIMITED='RATE_LIMITED';COMPLETED='COMPLETED';COMPLETED_WITH_ERRORS='COMPLETED_WITH_ERRORS';FAILED='FAILED';CANCELLED='CANCELLED'
class JobType(StrEnum):
    SCAN='SCAN';TARGET_SCAN='TARGET_SCAN';MIGRATION='MIGRATION';REMOVE='REMOVE';IMPORT='IMPORT';EXPORT='EXPORT'
class MigrationItemState(StrEnum):
    READY='READY';RETRY='RETRY';SUCCESS='SUCCESS';SKIPPED='SKIPPED';FAILED='FAILED'
class InviteResultCode(StrEnum):
    RATE_LIMIT='RATE_LIMIT';RATE_LIMIT_INDEFINITE='RATE_LIMIT_INDEFINITE';PRIVACY='PRIVACY';ALREADY_MEMBER='ALREADY_MEMBER';NOT_ELIGIBLE='NOT_ELIGIBLE';PERMISSION='PERMISSION';AUTH='AUTH';INVALID_USER='INVALID_USER';NETWORK_TRANSIENT='NETWORK_TRANSIENT';SERVER_TRANSIENT='SERVER_TRANSIENT';UNKNOWN='UNKNOWN'
class TargetCoverage(StrEnum):
    COMPLETE='COMPLETE';PARTIAL='PARTIAL';UNAVAILABLE='UNAVAILABLE'
class TargetMemberState(StrEnum):
    KNOWN_ABSENT='KNOWN_ABSENT';UNKNOWN_TARGET_STATE='UNKNOWN_TARGET_STATE'
